[theme]
base = "dark"
primaryColor = "#22c55e"            # accent (buttons, active tab)
backgroundColor = "#000000"         # pure jet black
secondaryBackgroundColor = "#0a0a0a" # sidebar/cards
textColor = "#e5e7eb"               # light gray text
